# Generated by Django 6.0.6 on 2026-08-21 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='vet_reports/%Y/%m/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_summarization', 'Pending Summarization'), ('summary_ready', 'Summary Ready'), ('summary_failed', 'Summary Failed')], default='pending_summarization', max_length=30)),
                ('error_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_reports', to='cattle.cattle')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vet Report',
                'verbose_name_plural': 'Vet Reports',
                'db_table': 'vet_reports',
                'ordering': ['-upload_date'],
            },
        ),
    ]
