# Generated by Django 6.0.6 on 2026-08-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Feed Log',
                'verbose_name_plural': 'Feed Logs',
                'db_table': 'feed_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_feed_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_milk_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_litre', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, help_text='(milk_revenue - feed_cost) / milk_revenue', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_summaries', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Cost Summary',
                'verbose_name_plural': 'Cost Summaries',
                'db_table': 'cost_summaries',
                'ordering': ['-year', '-month'],
                'unique_together': {('cattle', 'month', 'year')},
            },
        ),
    ]
