# Generated by Django 6.0.6 on 2026-08-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_lower', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confidence_upper', models.DecimalField(decimal_places=2, max_digits=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Production Forecast',
                'verbose_name_plural': 'Production Forecasts',
                'db_table': 'production_forecasts',
                'ordering': ['forecast_date'],
            },
        ),
    ]
