# Generated by Django 6.0.6 on 2026-08-21 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evening_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_litres', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='cattle.cattle')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_logs_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk Log',
                'verbose_name_plural': 'Milk Logs',
                'db_table': 'milk_logs',
                'ordering': ['-date'],
                'unique_together': {('cattle', 'date')},
            },
        ),
    ]
