# Generated by Django 6.0.6 on 2026-08-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='avg_daily_milk_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected average daily milk yield in litres', max_digits=6, null=True),
        ),
    ]
