# Generated by Django 6.0.6 on 2026-08-21 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialInsemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_date', models.DateField()),
                ('semen_bull_name', models.CharField(max_length=150)),
                ('semen_batch_id', models.CharField(max_length=100)),
                ('technician_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED_PREGNANT', 'Confirmed Pregnant'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_events', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Artificial Insemination',
                'verbose_name_plural': 'Artificial Inseminations',
                'db_table': 'artificial_inseminations',
                'ordering': ['-ai_date'],
            },
        ),
        migrations.CreateModel(
            name='BreedingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HEAT_DUE', 'Heat Due'), ('BEST_BREED_WINDOW', 'Best Breeding Window'), ('PREGNANCY_CHECK_DUE', 'Pregnancy Check Due'), ('CALVING_SOON', 'Calving Soon')], max_length=25)),
                ('scheduled_date', models.DateField()),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_alerts', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Breeding Alert',
                'verbose_name_plural': 'Breeding Alerts',
                'db_table': 'breeding_alerts',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='HeatCycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_date', models.DateField()),
                ('signs', models.TextField(blank=True, default='')),
                ('intensity', models.CharField(choices=[('WEAK', 'Weak'), ('MODERATE', 'Moderate'), ('STRONG', 'Strong')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_cycles', to='cattle.cattle')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_cycles_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heat Cycle Log',
                'verbose_name_plural': 'Heat Cycle Logs',
                'db_table': 'heat_cycle_logs',
                'ordering': ['-observed_date'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_date', models.DateField()),
                ('expected_calving_date', models.DateField()),
                ('actual_calving_date', models.DateField(blank=True, null=True)),
                ('calf_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancy', to='breeding.artificialinsemination')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Pregnancy Record',
                'verbose_name_plural': 'Pregnancy Records',
                'db_table': 'pregnancy_records',
                'ordering': ['-confirmed_date'],
            },
        ),
    ]
