"""
Cost Optimizer models.

FeedLog     — daily feed entry per cattle (total_cost auto-computed)
CostSummary — monthly aggregated cost vs milk yield report
"""
from django.db import models
from apps.cattle.models import Cattle


class FeedLog(models.Model):
    cattle = models.ForeignKey(
        Cattle, on_delete=models.CASCADE, related_name="feed_logs"
    )
    date = models.DateField()
    feed_type = models.CharField(max_length=100)
    quantity_kg = models.DecimalField(max_digits=8, decimal_places=2)
    cost_per_kg = models.DecimalField(max_digits=8, decimal_places=2)
    total_cost = models.DecimalField(
        max_digits=10, decimal_places=2, editable=False
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "feed_logs"
        ordering = ["-date"]
        verbose_name = "Feed Log"
        verbose_name_plural = "Feed Logs"

    def save(self, *args, **kwargs):
        # Auto-compute total (Req 7 AC2)
        self.total_cost = self.quantity_kg * self.cost_per_kg
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.cattle.tag_number} | {self.date} | {self.feed_type} | ₹{self.total_cost}"


class CostSummary(models.Model):
    """
    Monthly roll-up record generated by the Cost Optimizer.
    Stores aggregated feed cost, total milk yield, and derived metrics.
    """
    cattle = models.ForeignKey(
        Cattle, on_delete=models.CASCADE, related_name="cost_summaries"
    )
    month = models.PositiveSmallIntegerField()   # 1–12
    year = models.PositiveSmallIntegerField()
    total_feed_cost = models.DecimalField(max_digits=12, decimal_places=2)
    total_milk_litres = models.DecimalField(max_digits=10, decimal_places=2)
    cost_per_litre = models.DecimalField(
        max_digits=8, decimal_places=4, null=True, blank=True
    )
    profit_margin = models.DecimalField(
        max_digits=8, decimal_places=4, null=True, blank=True,
        help_text="(milk_revenue - feed_cost) / milk_revenue"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "cost_summaries"
        unique_together = [("cattle", "month", "year")]
        ordering = ["-year", "-month"]
        verbose_name = "Cost Summary"
        verbose_name_plural = "Cost Summaries"

    def __str__(self):
        return f"{self.cattle.tag_number} | {self.month:02d}/{self.year} | ₹{self.total_feed_cost}"
